version: '2'
services:

  # The Application
  myapp:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
     - mongo  
    environment:
      - "CLIENT_MONGO_HOST=mongo"
      - "MONGO_PORT=27019"
      - "CLIENT_DB_DATABASE=imessage"
      - "CLIENT_MONGO_USERNAME=karim"
      - "CLIENT_MONGO_PASSWORD=karim"
    ports:
      - 1337:1337
      
  mongo:
    command: mongod
    image: mongo:3.0.14
    volumes:
      - mongodata1:/data/db
      - mongoconfig1:/data/configdb
    ports:
        - "27019:27017"      

volumes:
  mongodata1:
  mongoconfig1:  
